
/* Generated by zsLibEventingTool */


#include "c_helpers.h"
#include <zsLib/types.h>
#include <zsLib/eventing/types.h>
#include <zsLib/SafeInt.h>

#include "c_org_ortc_OrtcLibWithDispatcher.h"
#include "../org_ortc_OrtcLibWithDispatcher.h"
#include "c_org_ortc_Dispatcher.h"

using namespace wrapper;

//------------------------------------------------------------------------------
void ORTC_WRAPPER_C_CALLING_CONVENTION org_ortc_OrtcLibWithDispatcher_SetupWithDispatcher(org_ortc_Dispatcher_t dispatcher)
{
  
}


namespace wrapper
{
  //----------------------------------------------------------------------------
  org_ortc_OrtcLibWithDispatcher_t org_ortc_OrtcLibWithDispatcher_wrapperToHandle(wrapper::org::ortc::OrtcLibWithDispatcherPtr value)
  {
    return 0;
  }

  //----------------------------------------------------------------------------
  wrapper::org::ortc::OrtcLibWithDispatcherPtr org_ortc_OrtcLibWithDispatcher_wrapperFromHandle(org_ortc_OrtcLibWithDispatcher_t handle)
  {
    return NULL;
  }


} /* namespace wrapper */
