// Generated by zsLibEventingTool


#include "cx_custom_Org_Ortc_MediaControl.h"

#include <webrtc/modules/video_capture/windows/video_capture_winrt.h>

//------------------------------------------------------------------------------
::Org::Ortc::MediaControl^ Org::Ortc::MediaControl::ToCx(wrapper::org::ortc::MediaControlPtr value)
{
  if (!value) return nullptr;
  auto result = ref new MediaControl(WrapperCreate{});
  result->native_ = value;
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::ortc::MediaControlPtr Org::Ortc::MediaControl::FromCx(::Org::Ortc::MediaControl^ value)
{
  if (nullptr == value) return wrapper::org::ortc::MediaControlPtr();
  return value->native_;
}

//------------------------------------------------------------------------------
Org::Ortc::MediaControl::MediaControl()
  : native_(wrapper::org::ortc::MediaControl::wrapper_create())
{
  native_->wrapper_init_org_ortc_MediaControl();
}

//------------------------------------------------------------------------------
Windows::Graphics::Display::DisplayOrientations Org::Ortc::MediaControl::DisplayOrientation::get()
{
  return webrtc::videocapturemodule::AppStateDispatcher::Instance()->GetOrientation();
}

//------------------------------------------------------------------------------
void Org::Ortc::MediaControl::DisplayOrientation::set(Windows::Graphics::Display::DisplayOrientations value)
{
  webrtc::videocapturemodule::AppStateDispatcher::Instance()->DisplayOrientationChanged(value);
}
