// Generated by zsLibEventingTool

#pragma once

#include <wrapper/generated/cx/types.h>
#include <wrapper/generated/zs_MessageQueue.h>

namespace Zs {



  public ref class MessageQueue sealed
  {
  internal:
    wrapper::zs::MessageQueuePtr native_;

    struct WrapperCreate {};
    MessageQueue(const WrapperCreate &) {}

    static MessageQueue^ ToCx(wrapper::zs::MessageQueuePtr value);
    static wrapper::zs::MessageQueuePtr FromCx(MessageQueue^ value);

  public:
    // ::zs::MessageQueue
    ::Zs::MessageQueue^ GetDefaultForUi();
  };

} // namespace Zs
